# Generated by Django 6.1.1 on 2026-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название номера')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Вместимость (чел.)')),
                ('homebyme_embed_url', models.URLField(blank=True, null=True, verbose_name='HomeByMe 3D-тур (URL)')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
