# Generated by Django 6.1.1 on 2026-09-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер этажа')),
                ('title', models.CharField(max_length=100, verbose_name='Название этажа')),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='floors/', verbose_name='2D-схема этажа')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='x_pos',
            field=models.IntegerField(default=50, help_text='От 0 до 100% слева направо', verbose_name='Позиция X (%)'),
        ),
        migrations.AddField(
            model_name='room',
            name='y_pos',
            field=models.IntegerField(default=50, help_text='От 0 до 100% сверху вниз', verbose_name='Позиция Y (%)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2, verbose_name='Вместимость (чел)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='homebyme_embed_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на 3D-тур HomeByMe'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь ($)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название номера'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.floor', verbose_name='Этаж'),
        ),
    ]
