# Generated by Django 6.1.1 on 2026-09-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_floor_room_x_pos_room_y_pos_alter_room_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='x_pos',
            field=models.IntegerField(default=50, verbose_name='Позиция X (%)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='y_pos',
            field=models.IntegerField(default=50, verbose_name='Позиция Y (%)'),
        ),
    ]
