# Generated by Django 6.1.1 on 2026-09-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_x_pos_alter_room_y_pos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('room_number', 'title'), 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AddField(
            model_name='room',
            name='housekeeping',
            field=models.CharField(choices=[('clean', 'Чисто'), ('dirty', 'Требует уборки'), ('inspected', 'Проверено менеджером'), ('out_of_service', 'Вне эксплуатации')], default='clean', max_length=20, verbose_name='Статус уборки'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Фото номера'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступен для бронирования'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, help_text='Например, 201', max_length=10, verbose_name='Номер комнаты'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 из 5'), (2, '2 из 5'), (3, '3 из 5'), (4, '4 из 5'), (5, '5 из 5')], verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Отзыв')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.room', verbose_name='Номер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_review_per_guest')],
            },
        ),
    ]
