# Generated by Django 6.1.1 on 2026-09-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_options_room_housekeeping_room_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название удобства')),
                ('icon_class', models.CharField(blank=True, help_text='Например: fa-solid fa-wifi', max_length=100, verbose_name='Иконка (CSS класс)')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.amenity', verbose_name='Удобства'),
        ),
    ]
