# Generated by Django 6.1.1 on 2026-09-23 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_amenity_room_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь ($)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='rooms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Сезонная цена',
                'verbose_name_plural': 'Сезонные цены',
                'ordering': ['start_date'],
            },
        ),
    ]
