# Generated by Django 6.1.1 on 2026-09-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_seasonalrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='homebyme_embed_url',
        ),
        migrations.AddField(
            model_name='room',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='rooms_3d/', verbose_name='3D-модель номера (.glb)'),
        ),
    ]
