# Generated by Django 6.1.1 on 2026-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_room_homebyme_embed_url_room_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='homebyme_embed_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на 3D-тур HomeByMe'),
        ),
    ]
