# Generated by Django 6.1.1 on 2026-09-22 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Менеджер отеля'), ('receptionist', 'Администратор стойки'), ('housekeeping', 'Служба уборки')], default='receptionist', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Рабочий телефон')),
                ('hired_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата приёма')),
                ('is_on_shift', models.BooleanField(default=True, verbose_name='На смене')),
                ('internal_note', models.TextField(blank=True, verbose_name='Заметка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Персонал',
                'ordering': ('user__last_name', 'user__first_name'),
            },
        ),
    ]
